import Footer from "./(platform)/_components/Footer";
import Navbar from "./(platform)/_components/Navbar";
import Loading from "./utils/loading";
import { Suspense } from "react";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chairs App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Suspense fallback={<Loading />}>
          <main className="container">{children}</main>
        </Suspense>

        <Footer />
      </body>
    </html>
  );
}
